### ISSUE TITLE
Using it without the android app?

### ISSUE THREAD

**Issue by cloudwalker87** [fastfend/homebridge-haieracbridge-platform#2]
Hi there, 

I'd be quite keen to use your homebridge plugin as I have the same AC model like you have (flexis plus). Unfortunately I don't have an android device and bstuf's plugin doesn't seem to work. Is there a way to use your plugin without using your android app? This would be amazing. Thanks.

**Comment by fastfend** [comment]
There is an option. Complicated but there is. Because I'm using crazy SDK taken out from SmartAir2 app, I found that their libs only works on ARM platforms, so no x86. But! Android 9 ARM_x86 image (with arm emulation) on Android Emulator allows to run this app. Tested today. This leads to another problem, right now my app only controls devices in the same network, as I know there is no option to connect Android Emulator directly to LAN. I'll try running my app on [android-x86](www.android-x86.org) and provide more information here. Moreover I should upload app to GitHub on Sunday or Monday

**Comment by cloudwalker87** [comment]
:-) gut stuff. Is the app required just for setup or does it need to run somewhere continuously to function? Btw good luck with your finals ;-)

**Comment by fastfend** [comment]
Sadly it is needed to let it working all the time. I've made it as a background service so no problem with things like restarting etc. Bridge app at this moment is very stable and it definitely works with model on supported models section. For now I have problem with two things. First, even though SmartAir2 app can access devices through internet my app can't. Something related to certficates. And second, it doesn't work with Tundra Plus series. Don't know why. Devices are being found but SDK can't establish connection. I'll publish it as it is right now, but still. Things to fix

P.S. I've just ended finals, but thanks anyway

**Comment by fastfend** [comment]
Damn I fixed issue with internet device connection. So, SmartAir2 uses SDK called uSDK, i found correct version of it many months ago BUT! After many wasted hours and tons of read logs i found that the native libs used by uSDK are older than used in SmartAir2 app. When i replaced native libs inside my uSDK suddenly everything started to work. Gosh being stubborn paid back

**Comment by fastfend** [comment]
Ok, here's answer for the issue: https://github.com/fastfend/HaierACBridge/wiki/How-to-install-it-without-Android-device%3F

**Comment by cloudwalker87** [comment]
Thanks Piotr, will give it a try!
